import HomeLayoutView from "@/components/views/homeLayoutView";
import type { Metadata } from "next";

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000"
  ),
  title: "Aiesec Surabaya",
  description: "Generated by Next Js",
  authors: { name: "Rengga Rendi Saputra", url: "https://github.com/Renggars" },
  icons: {
    icon: "/aiesecTitle.jpg",
  },
  openGraph: {
    title: "Aiesec Surabaya",
    description: "Generated by Next Js",
  },
};

export default function Home() {
  return (
    <div>
      <HomeLayoutView />
    </div>
  );
}
